# Generated by Django 2.2 on 2020-12-24 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': '图书信息', 'verbose_name_plural': '图书信息'},
        ),
        migrations.CreateModel(
            name='PeopleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('gender', models.SmallIntegerField(choices=[(0, 'boy'), (1, 'girl')], default=0)),
                ('description', models.CharField(max_length=128, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookInfo')),
            ],
            options={
                'verbose_name': '人物信息',
                'verbose_name_plural': '人物信息',
                'db_table': 'peopleinfo',
            },
        ),
    ]
